name: Deploy React App
on: push
jobs:
 test:
	runs-on: windows-latest
	steps:
		- name: Print to console  
			run: echo Hello GH Actions!
		- name: Print a few lines
			run: |
			  echo 1
			  echo 2
		- name: test app
			run: npm run test
 lint:
	runs-on: windows-latest
	needs: test
	steps:
		- name: Get repository code
			uses: actions/checkout@v3
		- name: ins dependecies
			run: npm ci
		- name: lint app
			run: npm run lint
 build:
	runs-on: windows-latest
	needs: lint // билд запуститься если линт успешен
	steps:
		- name: Get repository code
			uses: actions/checkout@v3
		- name: ins dependecies
			run: npm ci
		- name: build app
			run: npm run build
		- name: deploy
			run: echo deploying...
